version: '3'
services:

  web:
    image: node:15.0.1
    working_dir: /app
    command: npm run serve
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    depends_on:
      - storybook

  storybook:
    image: node:15.0.1
    working_dir: /app
    command: npm run storybook
    volumes:
      - ./app:/app
    ports:
      - 6006:6006
